#!/bin/bash -e

if [ -e /usr/local/sti/assemble ]; then
  source /usr/local/sti/assemble
else
  source ${STI_SCRIPTS_PATH}/assemble
fi

# Get access to `cake` shell command for generating DB schema and migrations
if [ -f ${HOME}/bin/composer.phar ]; then
	${HOME}/bin/composer.phar -d ${HOME} install
fi